### ISSUE TITLE
bool broken

### ISSUE THREAD

**Issue by jayvdb** [moreati/b-prefix-all-the-doctests#1]
See https://travis-ci.org/jayvdb/bibliograph.core/builds/108444977

On Python 2
```python
File "/home/travis/build/jayvdb/bibliograph.core/bibliograph/core/utils.py", line 259, in bibliograph.core.utils.bin_search
Failed example:
    bin_search('python') != ''
Exception raised:
    Traceback (most recent call last):
      File "/opt/python/2.7.9/lib/python2.7/doctest.py", line 1315, in __run
        compileflags, 1) in test.globs
      File "<doctest bibliograph.core.utils.bin_search[2]>", line 1, in <module>
        bin_search('python') != ''
      File "build/bdist.linux-x86_64/egg/pretext.py", line 166, in bdisplayhook
        _displayhook(value, brepr)
      File "build/bdist.linux-x86_64/egg/pretext.py", line 149, in _displayhook
        text = repr_fn(value)
      File "/opt/python/2.7.9/lib/python2.7/repr.py", line 24, in repr
        return self.repr1(x, self.maxlevel)
      File "/opt/python/2.7.9/lib/python2.7/repr.py", line 34, in repr1
...
```

On Python 3
```
File "/home/travis/build/jayvdb/bibliograph.core/bibliograph/core/utils.py", line 259, in bibliograph.core.utils.bin_search
Failed example:
    bin_search('python') != ''
Expected:
    True
Got:
    <bool instance at 7f445cf4e560>
```

**Comment by moreati** [comment]
Thank you for the report and the fix, I've released 0.0.4 with your fix
